services:
  - type: web
    name: om-swami-app
    env: python

    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm install && npm run dev && mv build dist

    startCommand: |
      cd backend && gunicorn app:app