services:
  - type: web
    name: om-swami-app
    env: python

    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend
      npm install
      npm run build

    startCommand: |
      cd backend
      gunicorn app:app